services:
  caddy:
    image: caddy:2.8
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_SCHEME: ${DOMAIN_SCHEME:-http}
      DOMAIN_NAME: ${DOMAIN_NAME:-localdev.me}
      TLS_ENTRY: ${TLS_ENTRY}
    volumes:
      - ./:/etc/caddy
      - ./Caddyfile/:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  kong:
    image: kong:3.9.0
    user: kong
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always
    environment:
      KONG_DATABASE: off
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: /usr/local/kong
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
      KONG_PLUGINS: bundled,prometheus
      KONG_LOG_LEVEL: ${KONG_LOG_LEVEL:-info}
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_GUI_LISTEN: "127.0.0.1:8002"
      KONG_ROUTER_FLAVOR: "expressions"
    volumes:
      - ./:/opt/kong
  
  backend:
    image: kennethreitz/httpbin
    restart: always
  
  frontend:
    image: nginx:latest  
    volumes:
      - ./frontend:/usr/share/nginx/html 
    restart: always

volumes:
  caddy_data:
  caddy_config: